version: '3'

services:
    php:
        build:
            context: ./
            dockerfile: php.dockerfile
        volumes:
            - ./:/app
        working_dir: /app

    postgres:
        image: postgres:9.6
        ports:
            - 5432:5432
        volumes:
            - data:/var/lib/postgresql/data

volumes:
    data:
